<?php

namespace Test\Slevomat\Client\Response;

use Slevomat\Client\Response\Success;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-11-15 at 23:36:49.
 */
class SuccessTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Success
     */
    protected $object;

    /**
     * Success test data
     * @var array 
     */
    public $testData = [
        'result' => true,
        'data' => [
            'token' => '123456789012345',
            'code' => '234567890-123',
            'voucherData' => ['title' => 'VoucherName']
        ],
        'error' => [
            'code' => 0,
            'message' => null
        ]
    ];

    /**
     * Get Method accessible
     * 
     * @param string $name
     * 
     * @return type
     */
    protected static function getMethod($name)
    {
        $class  = new \ReflectionClass('Slevomat\Client\Response\Success');
        $method = $class->getMethod($name);
        $method->setAccessible(true);
        return $method;
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Success($this->testData, 200);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * Test Constructor
     *
     * @covers Success::__construct
     */
    public function testConstructor()
    {
        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder(get_class($this->object))
            ->disableOriginalConstructor()
            ->getMockForAbstractClass();
        $mock->__construct($this->testData, 200);
    }

    /**
     * @covers Success::parseResponseData
     */
    public function testParseResponseData()
    {
        $parseResponseData = self::getMethod('parseResponseData');
        $result            = $parseResponseData->invokeArgs($this->object,
            [['data' => 'response']]);
    }

    /**
     * @covers Success::getData
     */
    public function testGetData()
    {
        $this->object->getData();
    }

    /**
     * @covers Slevomat\Client\Response\Success::getIterator
     */
    public function testGetIterator()
    {
        $this->object->getIterator();
    }

    /**
     * @covers Abstract::getResult
     */
    public function testGetResult()
    {
        $this->object->getResult();
    }

    /**
     * @covers Abstract::getHttpCode
     */
    public function testGetHttpCode()
    {
        $this->object->getHttpCode();
    }
}
